devices([
  "iPhone 17 Pro Max",
  "iPad Air 13-inch (M4)"
])
languages([
  "en-US",
  "es-ES",
  "de-DE",
  "fr-FR",
  "pt-BR",
  "nl-NL",
  "ja-JP",
  "it-IT",
  "sv-SE",
  "da-DK",
  "nb-NO",
  "fi-FI",
  "zh-Hans",
  "ru-RU",
  "pl-PL"
])
scheme("ConnectionsUITests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
xcodebuild_formatter("")
disable_xcpretty(true)
number_of_retries(0)
