devices([
  "iPhone 17 Pro Max",
  "iPad Air 13-inch (M4)"
])
languages([
  "en-US",
  "es-ES",
  "de-DE",
  "fr-FR",
  "pt-BR",
  "nl-NL",
  "ja",
  "it",
  "sv",
  "da",
  "no",
  "fi",
  "zh-Hans",
  "ru",
  "pl"
])
scheme("ConnectionsUITests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
xcodebuild_formatter("")
disable_xcpretty(true)
number_of_retries(0)
